"""workoutapi

Revision ID: d3e80f7b1e9d
Revises: abec3092ceb2
Create Date: 2024-05-03 20:56:01.445387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e80f7b1e9d'
down_revision = 'abec3092ceb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('centros_treinamentos_id', sa.Integer(), nullable=False))
    op.drop_constraint('atletas_centro_treinamento_id_fkey', 'atletas', type_='foreignkey')
    op.create_foreign_key(None, 'atletas', 'centros_treinamentos', ['centros_treinamentos_id'], ['pk_id'])
    op.drop_column('atletas', 'centro_treinamento_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('centro_treinamento_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.create_foreign_key('atletas_centro_treinamento_id_fkey', 'atletas', 'centros_treinamentos', ['centro_treinamento_id'], ['pk_id'])
    op.drop_column('atletas', 'centros_treinamentos_id')
    # ### end Alembic commands ###
